apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-mongousuarios
data:
  port: "8003"
  db_host: "mongodb:27017"
  database: db_microservicios_respuestas
#  username: root
#  password: sasa
  curso_url: "msvc-cursos:8002"
  application.yaml: |-
    config:
      texto: Configurando env por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando Developer ambiente
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando Produccion ambiente    

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres14:5432"
  database: msvc_cursos
#  username: postgres
#  password: sasa
  usuario_url: "msvc-usuarios:8001"
