apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: msvc-mongousuarios
  name: msvc-mongousuarios
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msvc-mongousuarios
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: msvc-mongousuarios
    spec:
      containers:
      - image: saymonset/usuariosmongo:latest
        name: usuariosmongo
        ports:
        - containerPort: 8003
        resources: {}
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name


status: {}
