apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        env:
          - name: saymon
            value: sasasimons
        volumeMounts:
          - name: data-mongo
            mountPath: /data/db
      volumes:
        - name: data-mongo
          persistentVolumeClaim:
            claimName: mongo-pvc
