apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        env:
          - name: SAYMON_HOST_TO_SHOW_IN_APPLICATION
            valueFrom:
              configMapKeyRef:
                name: msvc-mongousuarios
                key: db_host
          - name: USERNAME_ENV
            valueFrom:
              secretKeyRef:
                name: msvc-mongousuarios
                key: username
          - name: PASSWORD_ENV
            valueFrom:
              secretKeyRef:
                name: msvc-mongousuarios
                key: password
        volumeMounts:
          - name: data-mongo
            mountPath: /data/db
      volumes:
        - name: data-mongo
          persistentVolumeClaim:
            claimName: mongo-pvc
