#Borramos todas las imagenes
#docker image prune -a

# docker-compose up --help

#Docker hub
#Creamos un nombre exavto a lo que ncsitamos en docker hub para subir la imagen
#docker tag microservicio_blank_msvc-usuarios saymonset/usuarios
#docker push  saymonset/usuarios

version: "3.9"
services:
  mysql8:
    # Con este container_name, obligamos que el nombre se llame exactamente igual sin colocar un prefijo por default
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    # Con este container_name, obligamos que el nombre se llame exactamente igual sin colocar un prefijo por default
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    # Con este container_name, obligamos que el nombre se llame exactamente igual sin colocar un prefijo por default
    container_name: msvc-usuarios
    #Construimos la imagen con el Dockerfile que construimos manualmente
    build:
      # El contexto es el lugar de partida, donde se copian los archivos etc
      context: ./
      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-cursos:
    # Con este container_name, obligamos que el nombre se llame exactamente igual sin colocar un prefijo por default
    container_name: msvc-cursos
    build:
      # El contexto es el lugar de partida, donde se copian los archivos etc
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always
volumes:
  data-mysql:
    # Con este name, obligamos que el nombre se llame exactamente igual sin colocar un prefijo por default
    name: data-mysql
  data-postgres:
    # Con este name, obligamos que el nombre se llame exactamente igual sin colocar un prefijo por default
    name: data-postgres

networks:
  spring:
    name: spring