apiVersion: v1
kind: Secret
metadata:
  name: msvc-mongousuarios
type: Opaque
data:
  username: c2F5bW9u
  password: c2F5bW9u

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: c2FzYQ==