apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-07T13:58:05Z"
  labels:
    app: msvc-mongousuarios
  name: msvc-mongousuarios
  namespace: default
  resourceVersion: "577870"
  uid: 279e0401-b4ff-4c62-b77e-e246655ff44d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.129.214
  clusterIPs:
  - 10.105.129.214
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32737
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: msvc-mongousuarios
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
